### ISSUE TITLE
Error on parseLoops and parseConds

### ISSUE THREAD

**Issue by ceoslidi** [ceoslidi/firework#24]
View.php
34,35 Lines

**Comment by ceoslidi** [comment]
PHP Fatal error:  Uncaught Exception: Trying to get value of an undefined variable. in C:\OpenServer\domains\firework\firework\View.php:98
Stack trace:
#0 C:\OpenServer\domains\firework\firework\View.php(45): Firework\View->parseViewLoops()
#1 C:\OpenServer\domains\firework\app\controllers\FirstController.php(15): Firework\View->renderView()
#2 [internal function]: App\Controllers\FirstController->render()
#3 C:\OpenServer\domains\firework\firework\Router.php(61): call_user_func()
#4 C:\OpenServer\domains\firework\firework\Router.php(38): Firework\Router->request()
#5 [internal function]: Firework\Router->__destruct()
#6 {main}
  thrown in C:\OpenServer\domains\firework\firework\View.php on line 98
[Tue Feb 22 17:30:43 2022] 127.0.0.1:65173 Closing

**Comment by ceoslidi** [comment]
PHP Fatal error:  Uncaught TypeError: preg_match(): Argument #2 ($subject) must be of type string, array given in C:\OpenServer\domains\firework\firework\View.php:276
Stack trace:
#0 C:\OpenServer\domains\firework\firework\View.php(276): preg_match()
#1 C:\OpenServer\domains\firework\firework\View.php(48): Firework\View->parseViewExtends()
#2 C:\OpenServer\domains\firework\app\controllers\FirstController.php(16): Firework\View->renderView()
#3 [internal function]: App\Controllers\FirstController->render()
#4 C:\OpenServer\domains\firework\firework\Router.php(64): call_user_func()
#5 C:\OpenServer\domains\firework\firework\Router.php(41): Firework\Router->request()
#6 [internal function]: Firework\Router->__destruct()
#7 {main}
  thrown in C:\OpenServer\domains\firework\firework\View.php on line 276
